services:
  metabase:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: metabase
    ports:
      - "3000:3000"
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    networks:
      - gharchive_network
networks:
  gharchive_network:
    external: true