services:
  spark-master:
    image: bitnami/spark:3.5.5
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8989:8080"  # Web UI for Spark Master
      - "7077:7077"  # Spark Master port
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
    networks:
      - gharchive_network

  spark-worker:
    image: bitnami/spark:3.5.5
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
    networks:
      - gharchive_network

  jupyter-notebook:
    build:
        context: .
        dockerfile: Notebook.Dockerfile
    ports:
      - "8888:8888"  # Jupyter Notebook port
    volumes:
      - ./notebooks:/app/notebooks  # Mount local directory for notebooks
    environment:
      - JUPYTER_ENABLE_LAB=yes  # Enable JupyterLab interface
      - SPARK_MASTER=spark://spark-master:7077
    depends_on:
      - spark-master
      - spark-worker
    networks:
      - gharchive_network

networks:
  gharchive_network:
    external: true