import pyarrow as pa

gh_events_schema = pa.schema(
    [
        pa.field("event_type", pa.dictionary(pa.int8(), pa.string())),
        pa.field("actor_login", pa.string()),
        pa.field("repo_name", pa.string()),
        pa.field("created_at", pa.timestamp("s", tz="UTC")),
        pa.field("updated_at", pa.timestamp("s", tz="UTC")),
        pa.field("action", pa.dictionary(pa.int8(), pa.string())),
        pa.field("comment_id", pa.uint64()),
        pa.field("body", pa.string()),
        pa.field("path", pa.string()),
        pa.field("position", pa.int32()),
        pa.field("line", pa.int32()),
        pa.field("ref", pa.string()),
        pa.field("ref_type", pa.dictionary(pa.int8(), pa.string())),
        pa.field("creator_user_login", pa.string()),
        pa.field("number", pa.uint32()),
        pa.field("title", pa.string()),
        pa.field("labels", pa.list_(pa.string())),
        pa.field("state", pa.dictionary(pa.int8(), pa.string())),
        pa.field("locked", pa.uint8()),
        pa.field("assignee", pa.string()),
        pa.field("assignees", pa.list_(pa.string())),
        pa.field("comments", pa.uint32()),
        pa.field("author_association", pa.dictionary(pa.int8(), pa.string())),
        pa.field("closed_at", pa.timestamp("s", tz="UTC")),
        pa.field("merged_at", pa.timestamp("s", tz="UTC")),
        pa.field("merge_commit_sha", pa.string()),
        pa.field("requested_reviewers", pa.list_(pa.string())),
        pa.field("requested_teams", pa.list_(pa.string())),
        pa.field("head_ref", pa.string()),
        pa.field("head_sha", pa.string()),
        pa.field("base_ref", pa.string()),
        pa.field("base_sha", pa.string()),
        pa.field("merged", pa.uint8()),
        pa.field("mergeable", pa.uint8()),
        pa.field("rebaseable", pa.uint8()),
        pa.field("mergeable_state", pa.dictionary(pa.int8(), pa.string())),
        pa.field("merged_by", pa.string()),
        pa.field("review_comments", pa.uint32()),
        pa.field("maintainer_can_modify", pa.uint8()),
        pa.field("commits", pa.uint32()),
        pa.field("additions", pa.uint32()),
        pa.field("deletions", pa.uint32()),
        pa.field("changed_files", pa.uint32()),
        pa.field("diff_hunk", pa.string()),
        pa.field("original_position", pa.uint32()),
        pa.field("commit_id", pa.string()),
        pa.field("original_commit_id", pa.string()),
        pa.field("push_size", pa.uint32()),
        pa.field("push_distinct_size", pa.uint32()),
        pa.field("member_login", pa.string()),
        pa.field("release_tag_name", pa.string()),
        pa.field("release_name", pa.string()),
        pa.field("review_state", pa.dictionary(pa.int8(), pa.string())),
    ]
)
