services:
    minio:
        image: minio/minio:RELEASE.2025-02-28T09-55-16Z
        container_name: minio
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: minioadmin
        volumes:
            - ./data:/data
        command: server /data --console-address ":9001"
        networks:
            - gharchive_network    
        healthcheck:
            test: ["CMD", "curl", "--fail", "http://localhost:9000/minio/health/live"]
            interval: 30s
            timeout: 20s
            retries: 3

networks:
  gharchive_network:
    external: true